namespace Products.Catalog.Domain.Entities.Books
{
    public enum BookGenre
    {
        Fiction,
        NonFiction,
        Mystery,
        Fantasy,
        ScienceFiction,
        Biography,
        SelfHelp,
        Romance,
        Historical,
        Thriller,
        Horror,
        Poetry,
        YoungAdult,
        Children,
        Drama,
        Adventure,
        GraphicNovel,
        Classic,
        Cookbook,
        Spirituality,
        Science,
        History,
        Travel,
        Art,
        Psychology,
        Philosophy,
        Education,
        Music,
        Health,
        Business
    }
}